"""empty message

Revision ID: cfed66b82e53
Revises: 96fab812b67e
Create Date: 2022-05-21 23:12:47.404522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfed66b82e53'
down_revision = '96fab812b67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airports', 'name')
    # ### end Alembic commands ###
